
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 29 22:00:26 CST 2018
//----------------------------------------------------

package dash;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int FUNCTION = 11;
  public static final int LKEY = 51;
  public static final int GREATERTHAN_OP = 43;
  public static final int ADDFOR = 26;
  public static final int CHAR = 5;
  public static final int MULT_OP = 29;
  public static final int SIMCOM = 61;
  public static final int CASE = 22;
  public static final int INTEGER = 58;
  public static final int DOBCOM = 62;
  public static final int INT = 3;
  public static final int ADD_OP = 31;
  public static final int RBRAC = 50;
  public static final int EQUAL_OP = 38;
  public static final int FOR = 18;
  public static final int INTPTR = 4;
  public static final int SEMICOLON = 53;
  public static final int RPAR = 48;
  public static final int TYPE = 2;
  public static final int LESSTHAN_OP = 42;
  public static final int COMMA = 39;
  public static final int BOOL = 7;
  public static final int OR_OP = 41;
  public static final int ASSIGN = 33;
  public static final int MAIN = 12;
  public static final int IF = 16;
  public static final int DOT = 55;
  public static final int ID = 25;
  public static final int AND_OP = 40;
  public static final int SYMBS = 63;
  public static final int ADD_ASSIGN = 34;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int NOTEQUAL_OP = 46;
  public static final int MINUSFOR = 27;
  public static final int TRUE = 59;
  public static final int RKEY = 52;
  public static final int error = 1;
  public static final int DASH = 56;
  public static final int BREAK = 24;
  public static final int MINUS_OP = 32;
  public static final int DIV_ASSIGN = 37;
  public static final int SWITCH = 21;
  public static final int CHARPTR = 6;
  public static final int ARROW = 10;
  public static final int COLON = 54;
  public static final int ELSE = 17;
  public static final int LETTER = 57;
  public static final int READ = 14;
  public static final int WHILE = 19;
  public static final int DIV_OP = 30;
  public static final int DEFAULT = 23;
  public static final int GREATEREQUAL_OP = 45;
  public static final int LPAR = 47;
  public static final int STRING = 9;
  public static final int LBRAC = 49;
  public static final int TEXT = 64;
  public static final int FALSE = 60;
  public static final int MULT_ASSIGN = 36;
  public static final int LESSEQUAL_OP = 44;
  public static final int MINUS_ASSIGN = 35;
  public static final int BOOLPTR = 8;
  public static final int PRINT = 15;
  public static final int DO = 20;
  public static final int MULTFOR = 28;
}

