
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package dash;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int LKEY = 39;
  public static final int GREATERTHAN_OP = 31;
  public static final int CHAR = 5;
  public static final int MULT_OP = 17;
  public static final int SIMCOM = 50;
  public static final int INTEGER = 46;
  public static final int DOBCOM = 51;
  public static final int INT = 3;
  public static final int ADD_OP = 19;
  public static final int RBRAC = 38;
  public static final int FOR = 14;
  public static final int EQUAL_OP = 26;
  public static final int INTPTR = 4;
  public static final int SEMICOLON = 41;
  public static final int RPAR = 36;
  public static final int TYPE = 2;
  public static final int LESSTHAN_OP = 30;
  public static final int BLANK = 49;
  public static final int BOOL = 7;
  public static final int OR_OP = 29;
  public static final int ASSIGN = 21;
  public static final int IF = 12;
  public static final int DOT = 43;
  public static final int ID = 16;
  public static final int AND_OP = 28;
  public static final int ADD_ASSIGN = 22;
  public static final int EOF = 0;
  public static final int NOTEQUAL_OP = 34;
  public static final int TRUE = 47;
  public static final int RKEY = 40;
  public static final int error = 1;
  public static final int DASH = 44;
  public static final int MINUS_OP = 20;
  public static final int DIV_ASSIGN = 25;
  public static final int CHARPTR = 6;
  public static final int COLON = 42;
  public static final int ELSE = 13;
  public static final int LETTER = 45;
  public static final int READ = 10;
  public static final int WHILE = 15;
  public static final int DIV_OP = 18;
  public static final int COMMMA = 27;
  public static final int GREATEREQUAL_OP = 33;
  public static final int LPAR = 35;
  public static final int STRING = 9;
  public static final int LBRAC = 37;
  public static final int FALSE = 48;
  public static final int MULT_ASSIGN = 24;
  public static final int LESSEQUAL_OP = 32;
  public static final int MINUS_ASSIGN = 23;
  public static final int BOOLPTR = 8;
  public static final int PRINT = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TYPE",
  "INT",
  "INTPTR",
  "CHAR",
  "CHARPTR",
  "BOOL",
  "BOOLPTR",
  "STRING",
  "READ",
  "PRINT",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "ID",
  "MULT_OP",
  "DIV_OP",
  "ADD_OP",
  "MINUS_OP",
  "ASSIGN",
  "ADD_ASSIGN",
  "MINUS_ASSIGN",
  "MULT_ASSIGN",
  "DIV_ASSIGN",
  "EQUAL_OP",
  "COMMMA",
  "AND_OP",
  "OR_OP",
  "LESSTHAN_OP",
  "GREATERTHAN_OP",
  "LESSEQUAL_OP",
  "GREATEREQUAL_OP",
  "NOTEQUAL_OP",
  "LPAR",
  "RPAR",
  "LBRAC",
  "RBRAC",
  "LKEY",
  "RKEY",
  "SEMICOLON",
  "COLON",
  "DOT",
  "DASH",
  "LETTER",
  "INTEGER",
  "TRUE",
  "FALSE",
  "BLANK",
  "SIMCOM",
  "DOBCOM"
  };
}

