
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 20 16:38:49 CST 2018
//----------------------------------------------------

package dash;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int FUNCTION = 11;
  public static final int LKEY = 42;
  public static final int GREATERTHAN_OP = 34;
  public static final int CHAR = 5;
  public static final int MULT_OP = 20;
  public static final int SIMCOM = 53;
  public static final int INTEGER = 49;
  public static final int DOBCOM = 54;
  public static final int INT = 3;
  public static final int ADD_OP = 22;
  public static final int RBRAC = 41;
  public static final int FOR = 17;
  public static final int EQUAL_OP = 29;
  public static final int INTPTR = 4;
  public static final int SEMICOLON = 44;
  public static final int RPAR = 39;
  public static final int TYPE = 2;
  public static final int LESSTHAN_OP = 33;
  public static final int BLANK = 52;
  public static final int BOOL = 7;
  public static final int COMMA = 30;
  public static final int OR_OP = 32;
  public static final int ASSIGN = 24;
  public static final int MAIN = 12;
  public static final int IF = 15;
  public static final int DOT = 46;
  public static final int ID = 19;
  public static final int AND_OP = 31;
  public static final int ADD_ASSIGN = 25;
  public static final int EOF = 0;
  public static final int NOTEQUAL_OP = 37;
  public static final int TRUE = 50;
  public static final int RKEY = 43;
  public static final int error = 1;
  public static final int DASH = 47;
  public static final int MINUS_OP = 23;
  public static final int DIV_ASSIGN = 28;
  public static final int CHARPTR = 6;
  public static final int ARROW = 10;
  public static final int COLON = 45;
  public static final int ELSE = 16;
  public static final int LETTER = 48;
  public static final int READ = 13;
  public static final int WHILE = 18;
  public static final int DIV_OP = 21;
  public static final int GREATEREQUAL_OP = 36;
  public static final int LPAR = 38;
  public static final int STRING = 9;
  public static final int LBRAC = 40;
  public static final int FALSE = 51;
  public static final int MULT_ASSIGN = 27;
  public static final int LESSEQUAL_OP = 35;
  public static final int MINUS_ASSIGN = 26;
  public static final int BOOLPTR = 8;
  public static final int PRINT = 14;
}

